config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :products, only: [:index, :show]



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :photo

  belongs_to :user
  has_many :bookings

  validates :name, presence: true
  validates :category, presence: true

  # validates :lenght, presence: true, numericality: { only_integer: true }
  validates :description, presence: true
  validates :price, presence: true, numericality: { only_integer: true }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         
  has_many :bookings_as_a_renter, class_name: "Booking", dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :bookings_as_a_owner, class_name: "Booking", through: :products, source: :bookings

  validates :name, presence: true
  validates :first_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @bookings = Booking.all
    @mybookings = @bookmarks.where(user_id: current_user.id)
  end

  def show
  end

  def new
  end

  def create
    @booking = Booking.new
    @booking.product_id = paramas[:product_id]
    @booking.user_id = current_user.id
    if @booking.save
      redirect_to bookings_path
    else
      render :new, statut: :unprocessable_entity
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    if params[:query].present?
    sql_query = <<~SQL
    products.name ILIKE :query
    OR products.description ILIKE :query
  SQL
    @products = Product.where(sql_query, query: "%#{params[:query]}%")
  else
      @products = Product.all
  end
  end

  def show
    @product = Product.find(params[:id])
    @booking = Booking.new
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)
    @product.user_id = current_user.id
    if @wig.save
      redictect_to_products_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :category,
      :price,
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/index.html.erb
<h1>Bookings#index</h1>
<p>Find me in app/views/bookings/index.html.erb</p>

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>
<p>Find me in app/views/bookings/new.html.erb</p>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CampingSharing</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>CAMPINGSHARING</h1>

<p>Bienvenue sur le site de partage de matériel de camping</p>

<%  %>

<%= link_to "accéder aux catégories", products_path, class: 'btn button-essential'  %>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<h1>Listes des produits disponible:</h1>
<div class="product-card">
  <% @products.each do |product| %>
    <div class="product-card-details">
      <%= link_to product_path(product) do %>
        <%= image_tag(product.photo) %>
            <div><p>
              <%= product.name %>
              <div><%= product.description %>
              </div></p>
                <div>
                <p><%= product.price %> €</div></p>
                </div>
    </div>
      <% end %>
  <% end %>
</div>

app/views/products/new.html.erb
<h1>Products#new</h1>
<p>Find me in app/views/products/new.html.erb</p>

app/views/products/show.html.erb
Show
<%= @product.id %>
<% @product.name %>
<%= image_tag(@product.photo) %>
<%= @product.description %>


<br>
<br>
<br>
<div>
<%= link_to "retour aux catégories", products_path, class: 'btn button-essential'  %>
</div>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dfjlneir0/image/upload/v1676634909/Camping%20Sharing/Logo%20CS%20Alpha.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>